version: '3.8'

services:
  app:
    container_name: laravel_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/
  
  web:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
